matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: '3.6'
    - os: osx
      osx_image: xcode9.2
      # python: '3.6'

env:
  global:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

# See https://github.com/pypa/pip/issues/5236
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo pip install --upgrade pip
      pip install pipenv
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      # echo "Updating brew"
      # brew update
      echo "Installing python3"
      brew upgrade python
      pip3 install --upgrade pip setuptools wheel
      pip3 install pipenv
    fi
  - pipenv install --dev

script:
  - export VERSION=$(cat doc/VERSION)
  - pipenv run pyinstaller -y Subtitles.pyinstaller.spec
  - ls -lR dist
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      dmgbuild -s Subtitles.dmgbuild -D app=dist/Subtitles.app "Subtitles-${VERSION}" Subtitles-${VERSION}.dmg
    fi


before_deploy:
  - |
    case "$TRAVIS_OS_NAME" in
    'linux')
      local _release="Subtitles-Linux-amd64-$VERSION.tar.gz";;
      export RELEASE_FILE="dist/Subtitles-Linux-amd64-$VERSION.tar.gz";;
    'osx')
      export RELEASE_FILE="dist/Subtitles-$VERSION";;
    esac
  - "echo TODO: Package $RELEASE_FILE"


# deploy:
#   provider: releases
#   api_key:
#     secure: Yh1aLpZGOxxMDcyd79cee5c5nhKLyaU2FCF6x+kZyOf5H/tc9Njhy1vi9QZ7oF//q3tkJz699AnUl8mpa6jY2xSW4DMnDEP6y0ZnzBtrQNOoK2V5q0zC+uibBRBm/AeSRz54rPFIZWwpFwKuG9MGV5FxJQYfyht/0Axb228/tXgCDBwaC/AUVuVSeww3AK3jyH2tF1q+TxtIavkpK+a2CS6/hRYzQw4lqSRpSat0HTbv1YBKp0zlTVkoVxYzdK49tFRhrO+/6emaeUWv1LTeN4S3hQ3LQgn/T2h3fCbg58x1mJcFD2AALmx1kCOzNq6m8IuDiLDQHkPSKUZDvW9tY95gOK4eOUYoRfzocUrGj18mA3l2qiZXEKQc8C1FfSTRaKWkbzj6ZHZjtI89pNCxam2DB6sQM6Po0aplQgz/pI6kU4mVluo0ouwiI+yRTddExhp+B3cOp852CX4xAvr3UoP2uHuZIjFA4X9GCQWQaTpyrOSRpHXllcR3g3gaDVjFTubHALHRvK7ah9BlyNrrt1wPRp4t2bgbpRKL+7S9VyiVpybvNi4aEk02bDUpRVaXay+DX1W9ERT5QG4UPJLA44ffVHe6DctWe4q//9lvOrG7jjdxCtL8cA0zn6pLpUBRQ+EeHgHMwLHISLm0H7LL2Qbp3qX56hRD1+AJApym3SQ=
#   file: $RELEASE_FILE
#   on:
#     repo: philipbel/Subtitles
#     # branch: release


addons:
  apt:
    update: true
