language: generic

sudo:
  - false

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: '3.7'
      addons:
        apt:
          update: true
          packages:
            - nsis
      before_install:
        - sudo pip install --upgrade pipenv
        - curl -s https://packagecloud.io/install/repositories/packpack/packpack/script.deb.sh | sudo bash
      # script:
    - os: osx
      language: generic
      osx_image: xcode10.1
      addons:
        homebrew:
          update: true
          packages:
            - nsis
            - pipenv
      before_install:
        - npm install ManRueda/create-dmg
    - os: windows
      language: shell
      before_install:
        # See https://chocolatey.org/packages/python3
        # and https://docs.python.org/3/using/windows.html
        - choco install python3 --params "/PrependPath=1"
        - choco install nsis
        - choco install make
        - choco install zip
        # XXX: This is ugly.  Is there a better way?
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - pip install --upgrade pipenv

# before_install:

install:
  - touch Pipfile
  - make depends

script:
  - make package



before_deploy:
  - git config --local user.name "Philip Belemezov"
  - git config --local user.email "philip@belemezov.net"
  - export VERSION=$(cat doc/VERSION)
  # - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - export TRAVIS_TAG=v${VERSION}
  - echo "TRAVIS_TAG=${TRAVIS_TAG}"
  - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
  # TODO: Run tests and only then tag?
  # - git tag ${VERSION}.${TRAVIS_BUILD_NUMBER}
  - pwd
  - ls dist/
#   - case "$TRAVIS_OS_NAME" in
#     'linux')
#       export RELEASE_FILE="dist/Subtitles-$VERSION.zip";;
#     'osx')
#       export RELEASE_FILE="dist/Subtitles-$VERSION.dmg";;
#     'windows')
#       export RELEASE_FILE="dist/Subtitles-$VERSION.zip";;
#     esac
#   - "echo TODO: Package $RELEASE_FILE"


deploy:
  - provider: releases
    api_key:
      secure: Yh1aLpZGOxxMDcyd79cee5c5nhKLyaU2FCF6x+kZyOf5H/tc9Njhy1vi9QZ7oF//q3tkJz699AnUl8mpa6jY2xSW4DMnDEP6y0ZnzBtrQNOoK2V5q0zC+uibBRBm/AeSRz54rPFIZWwpFwKuG9MGV5FxJQYfyht/0Axb228/tXgCDBwaC/AUVuVSeww3AK3jyH2tF1q+TxtIavkpK+a2CS6/hRYzQw4lqSRpSat0HTbv1YBKp0zlTVkoVxYzdK49tFRhrO+/6emaeUWv1LTeN4S3hQ3LQgn/T2h3fCbg58x1mJcFD2AALmx1kCOzNq6m8IuDiLDQHkPSKUZDvW9tY95gOK4eOUYoRfzocUrGj18mA3l2qiZXEKQc8C1FfSTRaKWkbzj6ZHZjtI89pNCxam2DB6sQM6Po0aplQgz/pI6kU4mVluo0ouwiI+yRTddExhp+B3cOp852CX4xAvr3UoP2uHuZIjFA4X9GCQWQaTpyrOSRpHXllcR3g3gaDVjFTubHALHRvK7ah9BlyNrrt1wPRp4t2bgbpRKL+7S9VyiVpybvNi4aEk02bDUpRVaXay+DX1W9ERT5QG4UPJLA44ffVHe6DctWe4q//9lvOrG7jjdxCtL8cA0zn6pLpUBRQ+EeHgHMwLHISLm0H7LL2Qbp3qX56hRD1+AJApym3SQ=
    file_glob: true
    skip_cleanup: true
    file:
      - dist/Subtitles-*.dmg
      - dist/Subtitles-*.zip
      - dist/Subtitles-*-Setup.exe
      - dist/Subtitles-*.deb
      - dist/Subtitles-*.rpm
    on:
      repo: philipbel/Subtitles
      branch: master
      tags: true
