language: generic

sudo:
  - false

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: '3.7'
      env:
        - PYTHON=python
        - PIP=pip
          # PIP_INSTALL="sudo $PIP install"
        - PIP_INSTALL="$PIP install"
      addons:
        apt:
          update: true
          packages:
            - nsis
      script:
        - |
          # if $PIP --version | grep -Eq '^pip 19'; then
          #   PIP_VERSION_SUFFIX='=18.1'
          #   echo Installing pip-$PIP_VERSION_SUFFIX
          #   # $PYTHON -m pip install --upgrade pip-$PIP_VERSION_SUFFIX
          # fi
          # $PIP --version
    - os: osx
      language: generic
      osx_image: xcode10.1
      env:
        - PYTHON=python3
          PIP=pip3
          PIP_INSTALL="$PIP install"
      addons:
        homebrew:
          update: true
          packages:
            - nsis
            - pipenv
    - os: windows
      language: shell
      before_install:
        # See https://chocolatey.org/packages/python3
        # and https://docs.python.org/3/using/windows.html
        - choco update
        - choco install python3 --params "/PrependPath=1"
        - choco install nsis
        - choco install make
        - ls $(dirname $(which python))/Scripts
        - ls -l /c/ProgramData/chocolatey/bin


# if $PIP --version | grep -Eq '^pip 19'; then
#   echo Installing pip-$PIP_VERSION_SUFFIX
#   $PIP_INSTALL --upgrade pip$PIP_VERSION_SUFFIX
# fi

# before_install:
  # - which $PYTHON
  # - $PYTHON --version
  # - $PIP_INSTALL pipenv
  # - pipenv run python -m pip install pip==$PIP_VERSION
  # - pipenv run $PIP --version

install:
  - make build
  - make release

# script:
# - pipenv run pyinstaller -y Subtitles.pyinstaller.spec
# - ls -lR dist

# before_deploy:
#   - export VERSION=$(cat doc/VERSION)
#   - case "$TRAVIS_OS_NAME" in
#     'linux')
#       export RELEASE_FILE="dist/Subtitles-$VERSION";;
#     'osx')
#       export RELEASE_FILE="dist/Subtitles-$VERSION";;
#     esac
#   - "echo TODO: Package $RELEASE_FILE"


# deploy:
#   provider: releases
#   api_key:
#     secure: Yh1aLpZGOxxMDcyd79cee5c5nhKLyaU2FCF6x+kZyOf5H/tc9Njhy1vi9QZ7oF//q3tkJz699AnUl8mpa6jY2xSW4DMnDEP6y0ZnzBtrQNOoK2V5q0zC+uibBRBm/AeSRz54rPFIZWwpFwKuG9MGV5FxJQYfyht/0Axb228/tXgCDBwaC/AUVuVSeww3AK3jyH2tF1q+TxtIavkpK+a2CS6/hRYzQw4lqSRpSat0HTbv1YBKp0zlTVkoVxYzdK49tFRhrO+/6emaeUWv1LTeN4S3hQ3LQgn/T2h3fCbg58x1mJcFD2AALmx1kCOzNq6m8IuDiLDQHkPSKUZDvW9tY95gOK4eOUYoRfzocUrGj18mA3l2qiZXEKQc8C1FfSTRaKWkbzj6ZHZjtI89pNCxam2DB6sQM6Po0aplQgz/pI6kU4mVluo0ouwiI+yRTddExhp+B3cOp852CX4xAvr3UoP2uHuZIjFA4X9GCQWQaTpyrOSRpHXllcR3g3gaDVjFTubHALHRvK7ah9BlyNrrt1wPRp4t2bgbpRKL+7S9VyiVpybvNi4aEk02bDUpRVaXay+DX1W9ERT5QG4UPJLA44ffVHe6DctWe4q//9lvOrG7jjdxCtL8cA0zn6pLpUBRQ+EeHgHMwLHISLm0H7LL2Qbp3qX56hRD1+AJApym3SQ=
#   file: $RELEASE_FILE
#   on:
#     repo: philipbel/Subtitles
#     # branch: release
