language: generic

sudo:
  - false

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: '3.7'
      addons:
        apt:
          update: true
          packages:
            - nsis
      before_install:
        - sudo pip install pipenv
      # script:
    - os: osx
      language: generic
      osx_image: xcode10.1
      addons:
        homebrew:
          update: true
          packages:
            - nsis
            - pipenv
    - os: windows
      language: shell
      before_install:
        # See https://chocolatey.org/packages/python3
        # and https://docs.python.org/3/using/windows.html
        - choco install python3 --params "/PrependPath=1"
        - choco install nsis
        - choco install make
        - choco install zip
        # XXX: This is ugly.  Is there a better way?
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - pip install pipenv

before_install:
  - touch Pipfile
  - make depends

install:
  - make build
  - make package

# script:


# before_deploy:
#   - export VERSION=$(cat doc/VERSION)
#   - case "$TRAVIS_OS_NAME" in
#     'linux')
#       export RELEASE_FILE="dist/Subtitles-$VERSION";;
#     'osx')
#       export RELEASE_FILE="dist/Subtitles-$VERSION";;
#     esac
#   - "echo TODO: Package $RELEASE_FILE"


# deploy:
#   provider: releases
#   api_key:
#     secure: Yh1aLpZGOxxMDcyd79cee5c5nhKLyaU2FCF6x+kZyOf5H/tc9Njhy1vi9QZ7oF//q3tkJz699AnUl8mpa6jY2xSW4DMnDEP6y0ZnzBtrQNOoK2V5q0zC+uibBRBm/AeSRz54rPFIZWwpFwKuG9MGV5FxJQYfyht/0Axb228/tXgCDBwaC/AUVuVSeww3AK3jyH2tF1q+TxtIavkpK+a2CS6/hRYzQw4lqSRpSat0HTbv1YBKp0zlTVkoVxYzdK49tFRhrO+/6emaeUWv1LTeN4S3hQ3LQgn/T2h3fCbg58x1mJcFD2AALmx1kCOzNq6m8IuDiLDQHkPSKUZDvW9tY95gOK4eOUYoRfzocUrGj18mA3l2qiZXEKQc8C1FfSTRaKWkbzj6ZHZjtI89pNCxam2DB6sQM6Po0aplQgz/pI6kU4mVluo0ouwiI+yRTddExhp+B3cOp852CX4xAvr3UoP2uHuZIjFA4X9GCQWQaTpyrOSRpHXllcR3g3gaDVjFTubHALHRvK7ah9BlyNrrt1wPRp4t2bgbpRKL+7S9VyiVpybvNi4aEk02bDUpRVaXay+DX1W9ERT5QG4UPJLA44ffVHe6DctWe4q//9lvOrG7jjdxCtL8cA0zn6pLpUBRQ+EeHgHMwLHISLm0H7LL2Qbp3qX56hRD1+AJApym3SQ=
#   file: $RELEASE_FILE
#   on:
#     repo: philipbel/Subtitles
#     # branch: release
